# Generated by Django 3.1 on 2020-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.CharField(db_column='Task Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_column='Task Type'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='email',
            field=models.EmailField(db_column='Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_column='Task Type'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], db_column='Update Type', max_length=10),
        ),
    ]
